name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'readme.md'

jobs:

  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Set output
        id: set-output
        run: echo "::set-output name=commit_sha::${{ env.COMMIT_SHA }}"

      - name: Build Docker Image
        run: docker build -t ankitrajxd/simple-node-app:${{ env.COMMIT_SHA }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push ankitrajxd/simple-node-app:${{ env.COMMIT_SHA }}

    outputs:
      commit_sha: ${{ steps.set-output.outputs.commit_sha }}


      
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ankitrajxd/node-app-manifests.git
          token: ${{ secrets.GITHUB_TOKEN }}

          
      - name: Update the deployment manifest and Commit
        run: |
          git config --global user.email "ankitrajxd@gmail.com"
          git config --global user.name "GitHub Actions"

          sed -i 's|image: ankitrajxd/simple-node-app:.*|image: ankitrajxd/simple-node-app:${{ needs.build.outputs.commit_sha }}|' nodeapp.yaml
          git commit -am "Update deployment image to ankitrajxd/simple-node-app:${{ needs.build.outputs.commit_sha }}"
          git push origin main

