name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ankitrajxd/simple-node-app:${{ steps.vars.outputs.COMMIT_SHA }} .

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to dockerhub
        run: docker push ankitrajxd/simple-node-app:${{ steps.vars.outputs.COMMIT_SHA }}
