name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ankitrajxd/simple-node-app:${{ env.COMMIT_SHA }} .

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to dockerhub
        run: docker push ankitrajxd/simple-node-app:${{ env.COMMIT_SHA }}

  deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Set up SSH config
          run: |
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  
        - name: ssh into ec2 server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script: |
              docker pull ankitrajxd/simple-node-app:${{ env.COMMIT_SHA }}
              docker run -d -p 3000:3000 ankitrajxd/simple-node-app:${{ env.COMMIT_SHA }}
